export async function load({url,params}){
    const countryNamesNL = {
        AFG: "Afghanistan",
        ALB: "Albanië",
        DZA: "Algerije",
        AGO: "Angola",
        ATA: "Antarctica",
        ARG: "Argentinië",
        ARM: "Armenië",
        AUS: "Australië",
        AUT: "Oostenrijk",
        AZE: "Azerbeidzjan",
        BGD: "Bangladesh",
        BLR: "Wit-Rusland",
        BEL: "België",
        BLZ: "Belize",
        BEN: "Benin",
        BTN: "Bhutan",
        BOL: "Bolivia",
        BIH: "Bosnië en Herzegovina",
        BWA: "Botswana",
        BRA: "Brazilië",
        BRN: "Brunei",
        BGR: "Bulgarije",
        BFA: "Burkina Faso",
        BDI: "Burundi",
        KHM: "Cambodja",
        CMR: "Kameroen",
        CAN: "Canada",
        CAF: "Centraal-Afrikaanse Republiek",
        TCD: "Tsjaad",
        CHL: "Chili",
        CHN: "China",
        COL: "Colombia",
        CRI: "Costa Rica",
        HRV: "Kroatië",
        CUB: "Cuba",
        CYP: "Cyprus",
        CZE: "Tsjechië",
        COD: "Democratische Republiek Congo",
        DNK: "Denemarken",
        DJI: "Djibouti",
        DOM: "Dominicaanse Republiek",
        TLS: "Oost-Timor",
        ECU: "Ecuador",
        EGY: "Egypte",
        SLV: "El Salvador",
        GNQ: "Equatoriaal-Guinea",
        ERI: "Eritrea",
        EST: "Estland",
        ETH: "Ethiopië",
        FIN: "Finland",
        FRA: "Frankrijk",
        GAB: "Gabon",
        GMB: "Gambia",
        GEO: "Georgië",
        DEU: "Duitsland",
        GHA: "Ghana",
        GRC: "Griekenland",
        GRL: "Groenland",
        GTM: "Guatemala",
        GNB: "Guinee-Bissau",
        GIN: "Guinea",
        GUY: "Guyana",
        HTI: "Haïti",
        HND: "Honduras",
        HUN: "Hongarije",
        ISL: "IJsland",
        IND: "India",
        IDN: "Indonesië",
        IRN: "Iran",
        IRQ: "Irak",
        IRL: "Ierland",
        ISR: "Israël",
        ITA: "Italië",
        CIV: "Ivoorkust",
        JAM: "Jamaica",
        JPN: "Japan",
        JOR: "Jordanië",
        KAZ: "Kazachstan",
        KEN: "Kenia",
        KWT: "Koeweit",
        KGZ: "Kirgizië",
        LAO: "Laos",
        LVA: "Letland",
        LBN: "Libanon",
        LSO: "Lesotho",
        LBR: "Liberia",
        LBY: "Libië",
        LTU: "Litouwen",
        LUX: "Luxemburg",
        MKD: "Macedonië",
        MDG: "Madagaskar",
        MWI: "Malawi",
        MYS: "Maleisië",
        MLI: "Mali",
        MRT: "Mauritanië",
        MEX: "Mexico",
        MDA: "Moldavië",
        MNG: "Mongolië",
        MNE: "Montenegro",
        MAR: "Marokko",
        MOZ: "Mozambique",
        MMR: "Myanmar",
        NAM: "Namibië",
        NPL: "Nepal",
        NLD: "Nederland",
        NCL: "Nieuw-Caledonië",
        NZL: "Nieuw-Zeeland",
        NIC: "Nicaragua",
        NER: "Niger",
        NGA: "Nigeria",
        PRK: "Noord-Korea",
        NOR: "Noorwegen",
        OMN: "Oman",
        PAK: "Pakistan",
        PAN: "Panama",
        PNG: "Papoea-Nieuw-Guinea",
        PRY: "Paraguay",
        PER: "Peru",
        PHL: "Filipijnen",
        POL: "Polen",
        PRT: "Portugal",
        PRI: "Puerto Rico",
        QAT: "Qatar",
        SRB: "Servië",
        COG: "Republiek Congo",
        ROU: "Roemenië",
        RUS: "Rusland",
        RWA: "Rwanda",
        SAU: "Saudi-Arabië",
        SEN: "Senegal",
        SLE: "Sierra Leone",
        SVK: "Slowakije",
        SVN: "Slovenië",
        SLB: "Salomonseilanden",
        SOM: "Somalië",
        ZAF: "Zuid-Afrika",
        KOR: "Zuid-Korea",
        SSD: "Zuid-Soedan",
        ESP: "Spanje",
        LKA: "Sri Lanka",
        SDN: "Soedan",
        SUR: "Suriname",
        SWZ: "Swaziland",
        SWE: "Zweden",
        CHE: "Zwitserland",
        SYR: "Syrië",
        TWN: "Taiwan",
        TJK: "Tadzjikistan",
        THA: "Thailand",
        BHS: "Bahama's",
        TGO: "Togo",
        TTO: "Trinidad en Tobago",
        TUN: "Tunesië",
        TUR: "Turkije",
        TKM: "Turkmenistan",
        UGA: "Oeganda",
        UKR: "Oekraïne",
        ARE: "Verenigde Arabische Emiraten",
        GBR: "Verenigd Koninkrijk",
        TZA: "Tanzania",
        USA: "Verenigde Staten",
        URY: "Uruguay",
        UZB: "Oezbekistan",
        VUT: "Vanuatu",
        VEN: "Venezuela",
        VNM: "Vietnam",
        PSE: "Westelijke Jordaanoever",
        ESH: "Westelijke Sahara",
        YEM: "Jemen",
        ZMB: "Zambia",
        ZWE: "Zimbabwe",
    };

    const membersReponse = await fetch('https://fdnd.directus.app/items/person/'+params.id)
    const membersReponseData = await membersReponse.json()
    let DutchCountryName = countryNamesNL[membersReponseData.data["fav_country"]];

    return{member: membersReponseData.data, DutchCountryName: DutchCountryName}
}